require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
  - rubocop-faker

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'db/migrate/*'
    - 'vendor/**/*'
    - 'db/schema.rb'

Style/Documentation:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/OpenStructUse:
  Enabled: false
  