
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: <%= Rails.application.credentials.dig(:db, :user) %>

development:
  <<: *default
  host: localhost
  port: 5432
  database: test_task_app_development

test:
  <<: *default
  host: localhost
  port: 5432
  database: test_task_app_test

production:
  <<: *default
