
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: <%= Rails.application.credentials.dig(:db, :user) %>

development:
  <<: *default
  host: localhost
  port: 5432
  database: test_task_app_development

test:
  <<: *default
  host: localhost
  port: 5432
  database: test_task_app_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: test_task_app_production
  username: test_task_app
  password: <%= ENV['TEST_TASK_APP_RENDER_DATABASE_PASSWORD'] %>